### ISSUE TITLE
`pip install` error

### ISSUE THREAD

**Issue by mlovci** [daler/trackhub#17]
likely related to python3 incompatibility

```
MLovci-OSX:~ mlovci$ pip install trackhub
Collecting trackhub
  Downloading trackhub-0.1.3.tar.gz (557kB)
    100% |████████████████████████████████| 561kB 405kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/l0/b826yztn02b2mp7zt4g1_p440000gp/T/pip-build-t6v29t80/trackhub/setup.py", line 1, in <module>
        import ez_setup
      File "/private/var/folders/l0/b826yztn02b2mp7zt4g1_p440000gp/T/pip-build-t6v29t80/trackhub/ez_setup.py", line 106
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/l0/b826yztn02b2mp7zt4g1_p440000gp/T/pip-build-t6v29t80/trackhub
```

**Comment by daler** [comment]
Thanks for reporting this. Unfortunately, `fabric` is a dependency and is not Py3 compatible yet, so `trackhub` as a whole isn't either. 

A possible alternative is `invoke`, but it's apparently still alpha and subject to API changes, so I haven't invested the time into converting trackhub to use i.

Any other fabric replacement suggestions welcome!

http://www.fabfile.org/roadmap.html

I'll keep this issue open until I have Py3 support.

**Comment by daler** [comment]
By the way it's in [bioconda](https://bioconda.github.io/)  so the easiest workaround for now is to use it in an isolated py2 env:

```
conda create -n trackhub-env -c bioconda trackhub
```

**Comment by mlovci** [comment]
ok, thanks.

**Comment by daler** [comment]
Closing since we're now using rsync instead of fabric and supporting py3 as well.
