### ISSUE TITLE
ViewTrack url not mapped to bigDataUrl

### ISSUE THREAD

**Issue by mmendez12** [daler/trackhub#21]
I am trying to create a trackDb file with composite tracks and views however when I render the trackDb the url attribute is rendered as 'url' instead of 'bigDataUrl' as shown below:

```python
print ViewTrack(name='foo', url='bar', view='foobar')
>>> track foo
... shortLabel foo
... longLabel foo
... url bar
... view foobar
```
However when I use a simple Track the url attribute is rendered as 'bigDataUrl'.

I tried to add the 'bigDataUrl' parameter manually with add_params, it seems to be a valid parameter but it is not rendered in the final file.

Is there an other way to add a 'bigDataUrl' to a ViewTrack ?

Thanks

**Comment by daler** [comment]
Sorry it took me a while to get to this.

It's my understanding that the view tracks are aggregation tracks for multiple similar tracks (each of which have their own bigDataUrl) and as such there's no bigDataUrl for the ViewTrack. What bigDataUrl are you trying to add to a ViewTrack?

(see here for an example view track: https://genome.ucsc.edu/goldenpath/help/trackDb/trackDbHub.html#view)

**Comment by mmendez12** [comment]
Thanks for clarifying this issue. You are right, view tracks are not supposed to contain bigDataUrls. The trackDb file I used as referenced had this field and I was trying to produce the same file with your library, and did not see the gorilla
