### ISSUE TITLE
Track parent on/off

### ISSUE THREAD

**Issue by kapka2** [daler/trackhub#27]
I would like to have some flexibility around whether tracks contained in a composite track are on or off by default.  I can specify this by using one of the following options in the trackdb.txt file:
parent mycomposite on
parent mycomposite off

Would it be possible to add functionality to enable this?  Or would you be open to receiving a modified version of the package that includes this functionality?

**Comment by daler** [comment]
Certainly! If you have something working, submitting a pull request with a test would be the quickest way to add this.

**Comment by daler** [comment]
Closed in #28
