### ISSUE TITLE
ImportError: cannot import name Hub

### ISSUE THREAD

**Issue by endrebak** [daler/trackhub#31]
```bash
conda list | grep hub
trackhub                  0.1.3                    py27_0    bioconda
```

```python
$ python
>>> import trackhub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "trackhub.py", line 1, in <module>
    from trackhub import Hub, GenomesFile, Genome, TrackDb, Track
ImportError: cannot import name Hub
```

Is trackhub still maintained?

Anyways, learnt a lot about UCSC trackhubs just from reading the docs so thanks either way :)

**Comment by daler** [comment]
Yes, definitely; many changes on the `total-refactor` branch that I'm planning to release soon (next week or so).

**Comment by daler** [comment]
There are also a lot of new big* track types that I'd like to support. I think I'm going to get the `total-refactor` branch merged and released, then work on those other track types for a subsequent release.

**Comment by endrebak** [comment]
Cool, will the bug above be fixed in your new `total-refactor`ing? :)

**Comment by daler** [comment]
Yep. And py3 support.

**Comment by kapka2** [comment]
> There are also a lot of new big* track types that I'd like to support

Hi.  Are you planning to support bigInteract track types?  Do you have any concrete plans for implementation?

**Comment by daler** [comment]
Yes, definitely planning on supporting bigInteract tracks. I don't have any time frame for that . . . but pull requests happily accepted!

**Comment by daler** [comment]
Closing, because we now have py3 support and support for bigInteract (see [here](https://daler.github.io/trackhub/tracktypes/bigInteract.html) for an example). Conda release hopefully coming soon.
