### ISSUE TITLE
ssh_askpass error

### ISSUE THREAD

**Issue by msubirana** [daler/trackhub#35]
I am trying to upload my hub into a private server using this command
```
# Alternatively, we could upload directly to a web server (not run in this
# example):
trackhub.upload.upload_hub(
    hub=hub, host='host', user='user',
    remote_dir='remote_dir')
```
And I got the following error:

ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
Permission denied, please try again.

How can I fix the ssh password file?

**Comment by daler** [comment]
This has been open a long time, sorry about that. If this is still an issue please reopen and I'll take a look!
