### ISSUE TITLE
Inconsistent method names for adding tracks

### ISSUE THREAD

**Issue by evajason** [daler/trackhub#47]
Currently there is an inconsistent naming system for methods that add tracks. To add a track to an aggregate track or composite track, the method `add_subtrack` is used. When adding a track or a container track to a super track or directly to the trackdb, the method `add_tracks` is used.
 
Though these methods have different names, they have the same result of connecting the individual track to their parent container track. Additionally, when view tracks are added to a composite track, the method `add_view` is used.
 
The `add_tracks` convention can be extended to all situations where a track is added to another and `add_view` and `add_subtrack` would become obsolete. The class of a container track is declared when the track is made, therefore the package uses the appropriate method for appending it to the trackdb. Using a consistent name would make the package more user friendly.

**Comment by daler** [comment]
So I think the ones that need to change are:

| old method | new method|
|---|---|
|`CompositeTrack.add_subtrack`|`CompositeTrack.add_tracks`|
|`CompositeTrack.add_view`|`CompositeTrack.add_tracks`|
|`AggregateTrack.add_subtrack`|`AggregateTrack.add_tracks`| 

We already have:

- `ViewTrack.add_tracks`
- `SuperTrack.add_tracks`

so they won't need to change.

I'd like to keep backwards-compatibility, so the old methods should remain in place. Maybe add a [PendingDeprecationWarning](https://docs.python.org/3/library/exceptions.html#PendingDeprecationWarning) in the old methods?

For composite tracks, I think your proposed automatic handling of view tracks and regular tracks should work. I'm trying to think of corner cases where this would break but can't think of any. For example:
 
```python
# composite with one view, and then two tracks that are not 
# in the view but rather directly in the composite
composite.add_tracks([view, track1, track2])

# nesting those tracks within the view
composite.add_tracks(
        view.add_tracks([track1, track2])
)
```

Also, the new methods would make it ever-so-slightly cleaner, going from this:

```python
composite.add_view(view1)
composite.add_view(view2)
```

to:

```python
composite.add_tracks([view1, view2])
```

Another thing to consider is using `*args` in those methods, which would streamline a little bit more:

```python
composite.add_tracks(view1, view2)
```

I guess that last construct is a little less explicit, but I could go either way.

**Comment by daler** [comment]
After some internal discussion, let's go with supporting *all* signatures . . .

```python
composite.add_tracks([view1, track1])
composite.add_tracks(view1, track1)
composite.add_tracks(track2)

# but not this one; this should raise an exception complaining that
# not all args are instances of BaseTrack.
# Should write a test to make sure this is handled correctly
composite.add_tracks(view1, [track1, track2])
```

**Comment by daler** [comment]
Closing as this was added in #49
